# Training config
train:
  batch_size: 2
  epochs: 50
  start_epoch: 0
  learning_rate: 1.0e-4
  lambda_perc: 0.01
  log_file: "train_log.csv"
  checkpoint_weight_name: "vapswin2sr_checkpoint_weight.pth"
  checkpoint_optim_name: "vapswin2sr_checkpoint_optim.pth"
  final_model_name: "vapswin2sr_final.pth"

# Model config
model:
  upscale: 2
  img_size: 128
  in_chans: 3
  window_size: 8
  embed_dim: 90
  vab_d_atten: 90
  num_feat: 90
  img_range: 1.0
  depths: [6, 6, 6, 6]
  num_heads: [3, 3, 3, 3]
  resi_connection: '3conv'
  mlp_ratio: 2
  upsampler: 'pixelshuffle'

# Path Dataset
paths:
  train_lr: "Dataset\\dataset sr\\X2\\Train_LR"
  train_hr: "Dataset\\dataset sr\\X2\\Train"
  test_lr: "Dataset\\dataset sr\\X2\\Val_LR"
  test_hr: "Dataset\\dataset sr\\X2\\Val"
